import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from 'sonner';
const jetbrains = JetBrains_Mono({ 
  subsets: ["latin"],
  variable: "--font-mono", // We give it a variable name to use in Tailwind
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark"> 
      <body className={`${jetbrains.variable} font-mono bg-black text-white antialiased`}>
        <Navbar />
        {children}
        {/* <Footer /> */}
        <Toaster position="bottom-right" theme="dark" richColors />
      </body>
    </html>
  );
}
